services:
  node-app:
    environment:
      - NODE_ENV=production

# 1. docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
# OR
# 1. docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

# docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
